package com.claude.wmall.jxc.domain.store;

import java.util.List;

public class StoreCaiGouRkd extends StoreKudan {
    private Long banhao;
    private String danjubh;
    private String kuchunlx;
    private String gongyings;
    private String bumen;
    private String rukuck;
    private String baoguany;


    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.BANHAO
     *
     * @param banhao the value for STORE_CAIGOURKD.BANHAO
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.DANJUBH
     *
     * @return the value of STORE_CAIGOURKD.DANJUBH
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.DANJUBH
     *
     * @param danjubh the value for STORE_CAIGOURKD.DANJUBH
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.KUCHUNLX
     *
     * @return the value of STORE_CAIGOURKD.KUCHUNLX
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getKuchunlx() {
        return kuchunlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.KUCHUNLX
     *
     * @param kuchunlx the value for STORE_CAIGOURKD.KUCHUNLX
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setKuchunlx(String kuchunlx) {
        this.kuchunlx = kuchunlx == null ? null : kuchunlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.GONGYINGS
     *
     * @return the value of STORE_CAIGOURKD.GONGYINGS
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getGongyings() {
        return gongyings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.GONGYINGS
     *
     * @param gongyings the value for STORE_CAIGOURKD.GONGYINGS
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setGongyings(String gongyings) {
        this.gongyings = gongyings == null ? null : gongyings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.BUMEN
     *
     * @return the value of STORE_CAIGOURKD.BUMEN
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getBumen() {
        return bumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.BUMEN
     *
     * @param bumen the value for STORE_CAIGOURKD.BUMEN
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setBumen(String bumen) {
        this.bumen = bumen == null ? null : bumen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.RUKUCK
     *
     * @return the value of STORE_CAIGOURKD.RUKUCK
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getRukuck() {
        return rukuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.RUKUCK
     *
     * @param rukuck the value for STORE_CAIGOURKD.RUKUCK
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setRukuck(String rukuck) {
        this.rukuck = rukuck == null ? null : rukuck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_CAIGOURKD.BAOGUANY
     *
     * @return the value of STORE_CAIGOURKD.BAOGUANY
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getBaoguany() {
        return baoguany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_CAIGOURKD.BAOGUANY
     *
     * @param baoguany the value for STORE_CAIGOURKD.BAOGUANY
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setBaoguany(String baoguany) {
        this.baoguany = baoguany == null ? null : baoguany.trim();
    }

}