package com.claude.wmall.jxc.domain.store;

import java.util.List;

public class StoreYiKuD extends StoreKudan{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long banhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String rukuck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.RUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String rukugly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukuck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.CHUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukugly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_YIKUD.KUCUNLX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kucunlx;
    
    private List<StoreChuRuKls> churuklsList;

    public List<StoreChuRuKls> getChuruklsList() {
		return churuklsList;
	}

	public void setChuruklsList(List<StoreChuRuKls> churuklsList) {
		this.churuklsList = churuklsList;
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.BANHAO
     *
     * @return the value of STORE_YIKUD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.BANHAO
     *
     * @param banhao the value for STORE_YIKUD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.DANJUBH
     *
     * @return the value of STORE_YIKUD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.DANJUBH
     *
     * @param danjubh the value for STORE_YIKUD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.RUKUCK
     *
     * @return the value of STORE_YIKUD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getRukuck() {
        return rukuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.RUKUCK
     *
     * @param rukuck the value for STORE_YIKUD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setRukuck(String rukuck) {
        this.rukuck = rukuck == null ? null : rukuck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.RUKUGLY
     *
     * @return the value of STORE_YIKUD.RUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getRukugly() {
        return rukugly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.RUKUGLY
     *
     * @param rukugly the value for STORE_YIKUD.RUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setRukugly(String rukugly) {
        this.rukugly = rukugly == null ? null : rukugly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.CHUKUCK
     *
     * @return the value of STORE_YIKUD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukuck() {
        return chukuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.CHUKUCK
     *
     * @param chukuck the value for STORE_YIKUD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukuck(String chukuck) {
        this.chukuck = chukuck == null ? null : chukuck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.CHUKUGLY
     *
     * @return the value of STORE_YIKUD.CHUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukugly() {
        return chukugly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.CHUKUGLY
     *
     * @param chukugly the value for STORE_YIKUD.CHUKUGLY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukugly(String chukugly) {
        this.chukugly = chukugly == null ? null : chukugly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_YIKUD.KUCUNLX
     *
     * @return the value of STORE_YIKUD.KUCUNLX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKucunlx() {
        return kucunlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_YIKUD.KUCUNLX
     *
     * @param kucunlx the value for STORE_YIKUD.KUCUNLX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKucunlx(String kucunlx) {
        this.kucunlx = kucunlx == null ? null : kucunlx.trim();
    }
}