package com.claude.wmall.jxc.domain.store;

import java.util.List;

public class StoreHongZiXsckd extends StoreKudan{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long banhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.DIANDANH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String diandanh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.DIANDANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String diandanrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String yewuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String bumen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.KEHUMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kehumc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String changku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shouhuodz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Integer tiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_HONGZIXSCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chepaih;
    
    private List<StoreChuRuKls> churuklsList;

    public List<StoreChuRuKls> getChuruklsList() {
		return churuklsList;
	}

	public void setChuruklsList(List<StoreChuRuKls> churuklsList) {
		this.churuklsList = churuklsList;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.BANHAO
     *
     * @return the value of STORE_HONGZIXSCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.BANHAO
     *
     * @param banhao the value for STORE_HONGZIXSCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.DANJUBH
     *
     * @return the value of STORE_HONGZIXSCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.DANJUBH
     *
     * @param danjubh the value for STORE_HONGZIXSCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.DIANDANH
     *
     * @return the value of STORE_HONGZIXSCKD.DIANDANH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDiandanh() {
        return diandanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.DIANDANH
     *
     * @param diandanh the value for STORE_HONGZIXSCKD.DIANDANH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDiandanh(String diandanh) {
        this.diandanh = diandanh == null ? null : diandanh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.DIANDANRQ
     *
     * @return the value of STORE_HONGZIXSCKD.DIANDANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDiandanrq() {
        return diandanrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.DIANDANRQ
     *
     * @param diandanrq the value for STORE_HONGZIXSCKD.DIANDANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDiandanrq(String diandanrq) {
        this.diandanrq = diandanrq == null ? null : diandanrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.YEWUY
     *
     * @return the value of STORE_HONGZIXSCKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getYewuy() {
        return yewuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.YEWUY
     *
     * @param yewuy the value for STORE_HONGZIXSCKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYewuy(String yewuy) {
        this.yewuy = yewuy == null ? null : yewuy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.BUMEN
     *
     * @return the value of STORE_HONGZIXSCKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBumen() {
        return bumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.BUMEN
     *
     * @param bumen the value for STORE_HONGZIXSCKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBumen(String bumen) {
        this.bumen = bumen == null ? null : bumen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.KEHUMC
     *
     * @return the value of STORE_HONGZIXSCKD.KEHUMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKehumc() {
        return kehumc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.KEHUMC
     *
     * @param kehumc the value for STORE_HONGZIXSCKD.KEHUMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKehumc(String kehumc) {
        this.kehumc = kehumc == null ? null : kehumc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.CHANGKU
     *
     * @return the value of STORE_HONGZIXSCKD.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChangku() {
        return changku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.CHANGKU
     *
     * @param changku the value for STORE_HONGZIXSCKD.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChangku(String changku) {
        this.changku = changku == null ? null : changku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.SHOUHUODZ
     *
     * @return the value of STORE_HONGZIXSCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShouhuodz() {
        return shouhuodz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.SHOUHUODZ
     *
     * @param shouhuodz the value for STORE_HONGZIXSCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShouhuodz(String shouhuodz) {
        this.shouhuodz = shouhuodz == null ? null : shouhuodz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.CHEXING
     *
     * @return the value of STORE_HONGZIXSCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChexing() {
        return chexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.CHEXING
     *
     * @param chexing the value for STORE_HONGZIXSCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChexing(String chexing) {
        this.chexing = chexing == null ? null : chexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.TIJI
     *
     * @return the value of STORE_HONGZIXSCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Integer getTiji() {
        return tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.TIJI
     *
     * @param tiji the value for STORE_HONGZIXSCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setTiji(Integer tiji) {
        this.tiji = tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_HONGZIXSCKD.CHEPAIH
     *
     * @return the value of STORE_HONGZIXSCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChepaih() {
        return chepaih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_HONGZIXSCKD.CHEPAIH
     *
     * @param chepaih the value for STORE_HONGZIXSCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChepaih(String chepaih) {
        this.chepaih = chepaih == null ? null : chepaih.trim();
    }
}