package com.claude.wmall.jxc.domain.store;

public class StoreQiTaRkd extends StoreKudan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long banhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String yewuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String bumen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.GONGCHANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String gongchang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.CHEJIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chejian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.SHENGCHANX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shengchanx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.BANZHU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String banzhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.BANCI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String banci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.CANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String cangku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_QITARKD.KUGUANY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kuguany;

    private String gongyings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.BANHAO
     *
     * @return the value of STORE_QITARKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.BANHAO
     *
     * @param banhao the value for STORE_QITARKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.DANJUBH
     *
     * @return the value of STORE_QITARKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.DANJUBH
     *
     * @param danjubh the value for STORE_QITARKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.YEWUY
     *
     * @return the value of STORE_QITARKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getYewuy() {
        return yewuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.YEWUY
     *
     * @param yewuy the value for STORE_QITARKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYewuy(String yewuy) {
        this.yewuy = yewuy == null ? null : yewuy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.BUMEN
     *
     * @return the value of STORE_QITARKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBumen() {
        return bumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.BUMEN
     *
     * @param bumen the value for STORE_QITARKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBumen(String bumen) {
        this.bumen = bumen == null ? null : bumen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.GONGCHANG
     *
     * @return the value of STORE_QITARKD.GONGCHANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getGongchang() {
        return gongchang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.GONGCHANG
     *
     * @param gongchang the value for STORE_QITARKD.GONGCHANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setGongchang(String gongchang) {
        this.gongchang = gongchang == null ? null : gongchang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.CHEJIAN
     *
     * @return the value of STORE_QITARKD.CHEJIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChejian() {
        return chejian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.CHEJIAN
     *
     * @param chejian the value for STORE_QITARKD.CHEJIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChejian(String chejian) {
        this.chejian = chejian == null ? null : chejian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.SHENGCHANX
     *
     * @return the value of STORE_QITARKD.SHENGCHANX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShengchanx() {
        return shengchanx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.SHENGCHANX
     *
     * @param shengchanx the value for STORE_QITARKD.SHENGCHANX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShengchanx(String shengchanx) {
        this.shengchanx = shengchanx == null ? null : shengchanx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.BANZHU
     *
     * @return the value of STORE_QITARKD.BANZHU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBanzhu() {
        return banzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.BANZHU
     *
     * @param banzhu the value for STORE_QITARKD.BANZHU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanzhu(String banzhu) {
        this.banzhu = banzhu == null ? null : banzhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.BANCI
     *
     * @return the value of STORE_QITARKD.BANCI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBanci() {
        return banci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.BANCI
     *
     * @param banci the value for STORE_QITARKD.BANCI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanci(String banci) {
        this.banci = banci == null ? null : banci.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.CANGKU
     *
     * @return the value of STORE_QITARKD.CANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getCangku() {
        return cangku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.CANGKU
     *
     * @param cangku the value for STORE_QITARKD.CANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setCangku(String cangku) {
        this.cangku = cangku == null ? null : cangku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_QITARKD.KUGUANY
     *
     * @return the value of STORE_QITARKD.KUGUANY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKuguany() {
        return kuguany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_QITARKD.KUGUANY
     *
     * @param kuguany the value for STORE_QITARKD.KUGUANY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKuguany(String kuguany) {
        this.kuguany = kuguany == null ? null : kuguany.trim();
    }

    public String getGongyings() {
        return gongyings;
    }

    public void setGongyings(String gongyings) {
        this.gongyings = gongyings;
    }
}