package com.claude.wmall.jxc.domain.store;

import java.math.BigDecimal;

public class StoreKunCunPc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.PICIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long picih;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String changku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chanpianbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.PICI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String pici;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.DANJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal danjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.SHULIANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Integer shuliang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.BAOZIQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String baoziq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.SHENGCHANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shengchanrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUNCUNPC.SHIXIAORQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shixiaorq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.PICIH
     *
     * @return the value of STORE_KUNCUNPC.PICIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getPicih() {
        return picih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.PICIH
     *
     * @param picih the value for STORE_KUNCUNPC.PICIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setPicih(Long picih) {
        this.picih = picih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.CHANGKU
     *
     * @return the value of STORE_KUNCUNPC.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChangku() {
        return changku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.CHANGKU
     *
     * @param changku the value for STORE_KUNCUNPC.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChangku(String changku) {
        this.changku = changku == null ? null : changku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.CHANPIANBM
     *
     * @return the value of STORE_KUNCUNPC.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChanpianbm() {
        return chanpianbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.CHANPIANBM
     *
     * @param chanpianbm the value for STORE_KUNCUNPC.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChanpianbm(String chanpianbm) {
        this.chanpianbm = chanpianbm == null ? null : chanpianbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.PICI
     *
     * @return the value of STORE_KUNCUNPC.PICI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getPici() {
        return pici;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.PICI
     *
     * @param pici the value for STORE_KUNCUNPC.PICI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setPici(String pici) {
        this.pici = pici == null ? null : pici.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.DANJIA
     *
     * @return the value of STORE_KUNCUNPC.DANJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.DANJIA
     *
     * @param danjia the value for STORE_KUNCUNPC.DANJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjia(BigDecimal danjia) {
        this.danjia = danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.SHULIANG
     *
     * @return the value of STORE_KUNCUNPC.SHULIANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Integer getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.SHULIANG
     *
     * @param shuliang the value for STORE_KUNCUNPC.SHULIANG
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShuliang(Integer shuliang) {
        this.shuliang = shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.BAOZIQ
     *
     * @return the value of STORE_KUNCUNPC.BAOZIQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBaoziq() {
        return baoziq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.BAOZIQ
     *
     * @param baoziq the value for STORE_KUNCUNPC.BAOZIQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBaoziq(String baoziq) {
        this.baoziq = baoziq == null ? null : baoziq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.SHENGCHANRQ
     *
     * @return the value of STORE_KUNCUNPC.SHENGCHANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShengchanrq() {
        return shengchanrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.SHENGCHANRQ
     *
     * @param shengchanrq the value for STORE_KUNCUNPC.SHENGCHANRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShengchanrq(String shengchanrq) {
        this.shengchanrq = shengchanrq == null ? null : shengchanrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUNCUNPC.SHIXIAORQ
     *
     * @return the value of STORE_KUNCUNPC.SHIXIAORQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShixiaorq() {
        return shixiaorq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUNCUNPC.SHIXIAORQ
     *
     * @param shixiaorq the value for STORE_KUNCUNPC.SHIXIAORQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShixiaorq(String shixiaorq) {
        this.shixiaorq = shixiaorq == null ? null : shixiaorq.trim();
    }
}