package com.claude.wmall.jxc.domain.store;

public class StoreKuCunKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String changku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chanpianbm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.CHANGKU
     *
     * @return the value of STORE_KUCUN.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChangku() {
        return changku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.CHANGKU
     *
     * @param changku the value for STORE_KUCUN.CHANGKU
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChangku(String changku) {
        this.changku = changku == null ? null : changku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.CHANPIANBM
     *
     * @return the value of STORE_KUCUN.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChanpianbm() {
        return chanpianbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.CHANPIANBM
     *
     * @param chanpianbm the value for STORE_KUCUN.CHANPIANBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChanpianbm(String chanpianbm) {
        this.chanpianbm = chanpianbm == null ? null : chanpianbm.trim();
    }
}