package com.claude.wmall.jxc.domain.store;

import java.util.Date;
import java.util.List;

import com.claude.wmall.jxc.domain.common.WmallPager;

public class StoreKudan extends WmallPager{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.DANJUBH
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.DANJURQ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String danjurq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.BEIZHU
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String beizhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.SHENHER
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String shenher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.SHENHESJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private Date shenhesj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.SHENHEBJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String shenhebj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.FANSHENR
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String fanshenr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.FANSHENSJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String fanshensj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.RUKULX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String rukulx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.ZHUANHUAZT
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String zhuanhuazt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUDAN.KUDANLX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    private String kudanlx;

    private String yewuyuan;

    private Integer yewuyId;

    private List<StoreChuRuKls> churuklsList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.DANJUBH
     *
     * @return the value of STORE_KUDAN.DANJUBH
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.DANJUBH
     *
     * @param danjubh the value for STORE_KUDAN.DANJUBH
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.DANJURQ
     *
     * @return the value of STORE_KUDAN.DANJURQ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getDanjurq() {
        return danjurq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.DANJURQ
     *
     * @param danjurq the value for STORE_KUDAN.DANJURQ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setDanjurq(String danjurq) {
        this.danjurq = danjurq == null ? null : danjurq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.BEIZHU
     *
     * @return the value of STORE_KUDAN.BEIZHU
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.BEIZHU
     *
     * @param beizhu the value for STORE_KUDAN.BEIZHU
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.SHENHER
     *
     * @return the value of STORE_KUDAN.SHENHER
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getShenher() {
        return shenher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.SHENHER
     *
     * @param shenher the value for STORE_KUDAN.SHENHER
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setShenher(String shenher) {
        this.shenher = shenher == null ? null : shenher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.SHENHESJ
     *
     * @return the value of STORE_KUDAN.SHENHESJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public Date getShenhesj() {
        return shenhesj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.SHENHESJ
     *
     * @param shenhesj the value for STORE_KUDAN.SHENHESJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setShenhesj(Date shenhesj) {
        this.shenhesj = shenhesj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.SHENHEBJ
     *
     * @return the value of STORE_KUDAN.SHENHEBJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getShenhebj() {
        return shenhebj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.SHENHEBJ
     *
     * @param shenhebj the value for STORE_KUDAN.SHENHEBJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setShenhebj(String shenhebj) {
        this.shenhebj = shenhebj == null ? null : shenhebj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.FANSHENR
     *
     * @return the value of STORE_KUDAN.FANSHENR
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getFanshenr() {
        return fanshenr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.FANSHENR
     *
     * @param fanshenr the value for STORE_KUDAN.FANSHENR
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setFanshenr(String fanshenr) {
        this.fanshenr = fanshenr == null ? null : fanshenr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.FANSHENSJ
     *
     * @return the value of STORE_KUDAN.FANSHENSJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getFanshensj() {
        return fanshensj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.FANSHENSJ
     *
     * @param fanshensj the value for STORE_KUDAN.FANSHENSJ
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setFanshensj(String fanshensj) {
        this.fanshensj = fanshensj == null ? null : fanshensj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.RUKULX
     *
     * @return the value of STORE_KUDAN.RUKULX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getRukulx() {
        return rukulx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.RUKULX
     *
     * @param rukulx the value for STORE_KUDAN.RUKULX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setRukulx(String rukulx) {
        this.rukulx = rukulx == null ? null : rukulx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.ZHUANHUAZT
     *
     * @return the value of STORE_KUDAN.ZHUANHUAZT
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getZhuanhuazt() {
        return zhuanhuazt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.ZHUANHUAZT
     *
     * @param zhuanhuazt the value for STORE_KUDAN.ZHUANHUAZT
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setZhuanhuazt(String zhuanhuazt) {
        this.zhuanhuazt = zhuanhuazt == null ? null : zhuanhuazt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUDAN.KUDANLX
     *
     * @return the value of STORE_KUDAN.KUDANLX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public String getKudanlx() {
        return kudanlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUDAN.KUDANLX
     *
     * @param kudanlx the value for STORE_KUDAN.KUDANLX
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    public void setKudanlx(String kudanlx) {
        this.kudanlx = kudanlx == null ? null : kudanlx.trim();
    }

    public String getYewuyuan() {
        return yewuyuan;
    }

    public void setYewuyuan(String yewuyuan) {
        this.yewuyuan = yewuyuan;
    }

    public Integer getYewuyId() {
        return yewuyId;
    }

    public void setYewuyId(Integer yewuyId) {
        this.yewuyId = yewuyId;
    }

    public List<StoreChuRuKls> getChuruklsList() {
        return churuklsList;
    }

    public void setChuruklsList(List<StoreChuRuKls> churuklsList) {
        this.churuklsList = churuklsList;
    }
}