package com.claude.wmall.jxc.domain.store;

public class StoreKuCun extends StoreKuCunKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.CHANPINMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chanpinmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.CHANDI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chandi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.GUIGE
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String guige;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.JILIANGDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String jiliangdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_KUCUN.KUNCUNZL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Integer kuncunzl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.CHANPINMC
     *
     * @return the value of STORE_KUCUN.CHANPINMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChanpinmc() {
        return chanpinmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.CHANPINMC
     *
     * @param chanpinmc the value for STORE_KUCUN.CHANPINMC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChanpinmc(String chanpinmc) {
        this.chanpinmc = chanpinmc == null ? null : chanpinmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.CHANDI
     *
     * @return the value of STORE_KUCUN.CHANDI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChandi() {
        return chandi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.CHANDI
     *
     * @param chandi the value for STORE_KUCUN.CHANDI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChandi(String chandi) {
        this.chandi = chandi == null ? null : chandi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.GUIGE
     *
     * @return the value of STORE_KUCUN.GUIGE
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getGuige() {
        return guige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.GUIGE
     *
     * @param guige the value for STORE_KUCUN.GUIGE
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setGuige(String guige) {
        this.guige = guige == null ? null : guige.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.JILIANGDW
     *
     * @return the value of STORE_KUCUN.JILIANGDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getJiliangdw() {
        return jiliangdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.JILIANGDW
     *
     * @param jiliangdw the value for STORE_KUCUN.JILIANGDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setJiliangdw(String jiliangdw) {
        this.jiliangdw = jiliangdw == null ? null : jiliangdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_KUCUN.KUNCUNZL
     *
     * @return the value of STORE_KUCUN.KUNCUNZL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Integer getKuncunzl() {
        return kuncunzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_KUCUN.KUNCUNZL
     *
     * @param kuncunzl the value for STORE_KUCUN.KUNCUNZL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKuncunzl(Integer kuncunzl) {
        this.kuncunzl = kuncunzl;
    }
}