package com.claude.wmall.jxc.domain.store;

import java.math.BigDecimal;
import java.util.List;

public class StoreZhuangCheCkd extends StoreKudan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.BIANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long bianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukulx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String yewuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String bumen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.KEHUBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kehubm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.KEHUJC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kehujc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.KEHUQC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String kehuqc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.FAHUOCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String fahuock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.FAHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String fahuodz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chengyundw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.SHIFOUFY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shifoufy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.SHIFOUPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shifoupc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.JIHUAFHKSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String jihuafhkssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.JIHUAFHJSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String jihuafhjssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Integer tiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chepaih;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.SHIJILXDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shijilxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal gongli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal yunjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.GONGSHICDBL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal gongshicdbl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal yunfei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_ZHUANGCHECKD.FAHUOFS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String fahuofs;
    
    private List<StoreChuRuKls> churuklsList;

    public List<StoreChuRuKls> getChuruklsList() {
		return churuklsList;
	}

	public void setChuruklsList(List<StoreChuRuKls> churuklsList) {
		this.churuklsList = churuklsList;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.BIANHAO
     *
     * @return the value of STORE_ZHUANGCHECKD.BIANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBianhao() {
        return bianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.BIANHAO
     *
     * @param bianhao the value for STORE_ZHUANGCHECKD.BIANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBianhao(Long bianhao) {
        this.bianhao = bianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.DANJUBH
     *
     * @return the value of STORE_ZHUANGCHECKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.DANJUBH
     *
     * @param danjubh the value for STORE_ZHUANGCHECKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.CHUKULX
     *
     * @return the value of STORE_ZHUANGCHECKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukulx() {
        return chukulx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.CHUKULX
     *
     * @param chukulx the value for STORE_ZHUANGCHECKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukulx(String chukulx) {
        this.chukulx = chukulx == null ? null : chukulx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.YEWUY
     *
     * @return the value of STORE_ZHUANGCHECKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getYewuy() {
        return yewuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.YEWUY
     *
     * @param yewuy the value for STORE_ZHUANGCHECKD.YEWUY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYewuy(String yewuy) {
        this.yewuy = yewuy == null ? null : yewuy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.BUMEN
     *
     * @return the value of STORE_ZHUANGCHECKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getBumen() {
        return bumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.BUMEN
     *
     * @param bumen the value for STORE_ZHUANGCHECKD.BUMEN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBumen(String bumen) {
        this.bumen = bumen == null ? null : bumen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.KEHUBM
     *
     * @return the value of STORE_ZHUANGCHECKD.KEHUBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKehubm() {
        return kehubm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.KEHUBM
     *
     * @param kehubm the value for STORE_ZHUANGCHECKD.KEHUBM
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKehubm(String kehubm) {
        this.kehubm = kehubm == null ? null : kehubm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.KEHUJC
     *
     * @return the value of STORE_ZHUANGCHECKD.KEHUJC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKehujc() {
        return kehujc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.KEHUJC
     *
     * @param kehujc the value for STORE_ZHUANGCHECKD.KEHUJC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKehujc(String kehujc) {
        this.kehujc = kehujc == null ? null : kehujc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.KEHUQC
     *
     * @return the value of STORE_ZHUANGCHECKD.KEHUQC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getKehuqc() {
        return kehuqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.KEHUQC
     *
     * @param kehuqc the value for STORE_ZHUANGCHECKD.KEHUQC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setKehuqc(String kehuqc) {
        this.kehuqc = kehuqc == null ? null : kehuqc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.FAHUOCK
     *
     * @return the value of STORE_ZHUANGCHECKD.FAHUOCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getFahuock() {
        return fahuock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.FAHUOCK
     *
     * @param fahuock the value for STORE_ZHUANGCHECKD.FAHUOCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setFahuock(String fahuock) {
        this.fahuock = fahuock == null ? null : fahuock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.FAHUODZ
     *
     * @return the value of STORE_ZHUANGCHECKD.FAHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getFahuodz() {
        return fahuodz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.FAHUODZ
     *
     * @param fahuodz the value for STORE_ZHUANGCHECKD.FAHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setFahuodz(String fahuodz) {
        this.fahuodz = fahuodz == null ? null : fahuodz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.CHENGYUNDW
     *
     * @return the value of STORE_ZHUANGCHECKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChengyundw() {
        return chengyundw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.CHENGYUNDW
     *
     * @param chengyundw the value for STORE_ZHUANGCHECKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChengyundw(String chengyundw) {
        this.chengyundw = chengyundw == null ? null : chengyundw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.SHIFOUFY
     *
     * @return the value of STORE_ZHUANGCHECKD.SHIFOUFY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShifoufy() {
        return shifoufy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.SHIFOUFY
     *
     * @param shifoufy the value for STORE_ZHUANGCHECKD.SHIFOUFY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShifoufy(String shifoufy) {
        this.shifoufy = shifoufy == null ? null : shifoufy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.SHIFOUPC
     *
     * @return the value of STORE_ZHUANGCHECKD.SHIFOUPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShifoupc() {
        return shifoupc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.SHIFOUPC
     *
     * @param shifoupc the value for STORE_ZHUANGCHECKD.SHIFOUPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShifoupc(String shifoupc) {
        this.shifoupc = shifoupc == null ? null : shifoupc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.JIHUAFHKSSJ
     *
     * @return the value of STORE_ZHUANGCHECKD.JIHUAFHKSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getJihuafhkssj() {
        return jihuafhkssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.JIHUAFHKSSJ
     *
     * @param jihuafhkssj the value for STORE_ZHUANGCHECKD.JIHUAFHKSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setJihuafhkssj(String jihuafhkssj) {
        this.jihuafhkssj = jihuafhkssj == null ? null : jihuafhkssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.JIHUAFHJSSJ
     *
     * @return the value of STORE_ZHUANGCHECKD.JIHUAFHJSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getJihuafhjssj() {
        return jihuafhjssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.JIHUAFHJSSJ
     *
     * @param jihuafhjssj the value for STORE_ZHUANGCHECKD.JIHUAFHJSSJ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setJihuafhjssj(String jihuafhjssj) {
        this.jihuafhjssj = jihuafhjssj == null ? null : jihuafhjssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.CHEXING
     *
     * @return the value of STORE_ZHUANGCHECKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChexing() {
        return chexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.CHEXING
     *
     * @param chexing the value for STORE_ZHUANGCHECKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChexing(String chexing) {
        this.chexing = chexing == null ? null : chexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.TIJI
     *
     * @return the value of STORE_ZHUANGCHECKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Integer getTiji() {
        return tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.TIJI
     *
     * @param tiji the value for STORE_ZHUANGCHECKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setTiji(Integer tiji) {
        this.tiji = tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.CHEPAIH
     *
     * @return the value of STORE_ZHUANGCHECKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChepaih() {
        return chepaih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.CHEPAIH
     *
     * @param chepaih the value for STORE_ZHUANGCHECKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChepaih(String chepaih) {
        this.chepaih = chepaih == null ? null : chepaih.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.SHIJILXDH
     *
     * @return the value of STORE_ZHUANGCHECKD.SHIJILXDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShijilxdh() {
        return shijilxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.SHIJILXDH
     *
     * @param shijilxdh the value for STORE_ZHUANGCHECKD.SHIJILXDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShijilxdh(String shijilxdh) {
        this.shijilxdh = shijilxdh == null ? null : shijilxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.GONGLI
     *
     * @return the value of STORE_ZHUANGCHECKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getGongli() {
        return gongli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.GONGLI
     *
     * @param gongli the value for STORE_ZHUANGCHECKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setGongli(BigDecimal gongli) {
        this.gongli = gongli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.YUNJIA
     *
     * @return the value of STORE_ZHUANGCHECKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getYunjia() {
        return yunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.YUNJIA
     *
     * @param yunjia the value for STORE_ZHUANGCHECKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYunjia(BigDecimal yunjia) {
        this.yunjia = yunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.GONGSHICDBL
     *
     * @return the value of STORE_ZHUANGCHECKD.GONGSHICDBL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getGongshicdbl() {
        return gongshicdbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.GONGSHICDBL
     *
     * @param gongshicdbl the value for STORE_ZHUANGCHECKD.GONGSHICDBL
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setGongshicdbl(BigDecimal gongshicdbl) {
        this.gongshicdbl = gongshicdbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.YUNFEI
     *
     * @return the value of STORE_ZHUANGCHECKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getYunfei() {
        return yunfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.YUNFEI
     *
     * @param yunfei the value for STORE_ZHUANGCHECKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYunfei(BigDecimal yunfei) {
        this.yunfei = yunfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_ZHUANGCHECKD.FAHUOFS
     *
     * @return the value of STORE_ZHUANGCHECKD.FAHUOFS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getFahuofs() {
        return fahuofs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_ZHUANGCHECKD.FAHUOFS
     *
     * @param fahuofs the value for STORE_ZHUANGCHECKD.FAHUOFS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setFahuofs(String fahuofs) {
        this.fahuofs = fahuofs == null ? null : fahuofs.trim();
    }
}