package com.claude.wmall.jxc.domain.store;

import java.math.BigDecimal;

public class StoreDiaoBoRkd  extends StoreKudan{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long banhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.CHUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukubgy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukuck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.RUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String rukubgy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String rukuck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chengyundw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String luxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String tiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chepaih;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String jihuafhrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shouhuodz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.SHIFOUGDYF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shifougdyf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBORKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal yunfei;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.BANHAO
     *
     * @return the value of STORE_DIAOBORKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.BANHAO
     *
     * @param banhao the value for STORE_DIAOBORKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.DANJUBH
     *
     * @return the value of STORE_DIAOBORKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.DANJUBH
     *
     * @param danjubh the value for STORE_DIAOBORKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.CHUKUBGY
     *
     * @return the value of STORE_DIAOBORKD.CHUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukubgy() {
        return chukubgy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.CHUKUBGY
     *
     * @param chukubgy the value for STORE_DIAOBORKD.CHUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukubgy(String chukubgy) {
        this.chukubgy = chukubgy == null ? null : chukubgy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.CHUKUCK
     *
     * @return the value of STORE_DIAOBORKD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukuck() {
        return chukuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.CHUKUCK
     *
     * @param chukuck the value for STORE_DIAOBORKD.CHUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukuck(String chukuck) {
        this.chukuck = chukuck == null ? null : chukuck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.RUKUBGY
     *
     * @return the value of STORE_DIAOBORKD.RUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getRukubgy() {
        return rukubgy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.RUKUBGY
     *
     * @param rukubgy the value for STORE_DIAOBORKD.RUKUBGY
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setRukubgy(String rukubgy) {
        this.rukubgy = rukubgy == null ? null : rukubgy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.RUKUCK
     *
     * @return the value of STORE_DIAOBORKD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getRukuck() {
        return rukuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.RUKUCK
     *
     * @param rukuck the value for STORE_DIAOBORKD.RUKUCK
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setRukuck(String rukuck) {
        this.rukuck = rukuck == null ? null : rukuck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.CHENGYUNDW
     *
     * @return the value of STORE_DIAOBORKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChengyundw() {
        return chengyundw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.CHENGYUNDW
     *
     * @param chengyundw the value for STORE_DIAOBORKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChengyundw(String chengyundw) {
        this.chengyundw = chengyundw == null ? null : chengyundw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.LUXIAN
     *
     * @return the value of STORE_DIAOBORKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getLuxian() {
        return luxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.LUXIAN
     *
     * @param luxian the value for STORE_DIAOBORKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setLuxian(String luxian) {
        this.luxian = luxian == null ? null : luxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.CHEXING
     *
     * @return the value of STORE_DIAOBORKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChexing() {
        return chexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.CHEXING
     *
     * @param chexing the value for STORE_DIAOBORKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChexing(String chexing) {
        this.chexing = chexing == null ? null : chexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.TIJI
     *
     * @return the value of STORE_DIAOBORKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getTiji() {
        return tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.TIJI
     *
     * @param tiji the value for STORE_DIAOBORKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setTiji(String tiji) {
        this.tiji = tiji == null ? null : tiji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.CHEPAIH
     *
     * @return the value of STORE_DIAOBORKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChepaih() {
        return chepaih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.CHEPAIH
     *
     * @param chepaih the value for STORE_DIAOBORKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChepaih(String chepaih) {
        this.chepaih = chepaih == null ? null : chepaih.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.JIHUAFHRQ
     *
     * @return the value of STORE_DIAOBORKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getJihuafhrq() {
        return jihuafhrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.JIHUAFHRQ
     *
     * @param jihuafhrq the value for STORE_DIAOBORKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setJihuafhrq(String jihuafhrq) {
        this.jihuafhrq = jihuafhrq == null ? null : jihuafhrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.SHOUHUODZ
     *
     * @return the value of STORE_DIAOBORKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShouhuodz() {
        return shouhuodz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.SHOUHUODZ
     *
     * @param shouhuodz the value for STORE_DIAOBORKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShouhuodz(String shouhuodz) {
        this.shouhuodz = shouhuodz == null ? null : shouhuodz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.SHIFOUGDYF
     *
     * @return the value of STORE_DIAOBORKD.SHIFOUGDYF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShifougdyf() {
        return shifougdyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.SHIFOUGDYF
     *
     * @param shifougdyf the value for STORE_DIAOBORKD.SHIFOUGDYF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShifougdyf(String shifougdyf) {
        this.shifougdyf = shifougdyf == null ? null : shifougdyf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBORKD.YUNFEI
     *
     * @return the value of STORE_DIAOBORKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getYunfei() {
        return yunfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBORKD.YUNFEI
     *
     * @param yunfei the value for STORE_DIAOBORKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYunfei(BigDecimal yunfei) {
        this.yunfei = yunfei;
    }


}