package com.claude.wmall.jxc.domain.store;

import java.math.BigDecimal;
import java.util.List;

public class StoreDiaoBoCkd extends StoreKudan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Long banhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String danjubh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chukulx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.DIAORUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String diaoruf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.DIAOCHUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String diaochuf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chengyundw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String luxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal tiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String chepaih;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String jihuafhrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.SHIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shiji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.LIANXIDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String lianxidh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private String shouhuodz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal gongli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private Integer yunjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STORE_DIAOBOCKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    private BigDecimal yunfei;
    
    
    private List<StoreChuRuKls> churuklsList;

    public List<StoreChuRuKls> getChuruklsList() {
		return churuklsList;
	}

	public void setChuruklsList(List<StoreChuRuKls> churuklsList) {
		this.churuklsList = churuklsList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.BANHAO
     *
     * @return the value of STORE_DIAOBOCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Long getBanhao() {
        return banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.BANHAO
     *
     * @param banhao the value for STORE_DIAOBOCKD.BANHAO
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setBanhao(Long banhao) {
        this.banhao = banhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.DANJUBH
     *
     * @return the value of STORE_DIAOBOCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDanjubh() {
        return danjubh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.DANJUBH
     *
     * @param danjubh the value for STORE_DIAOBOCKD.DANJUBH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDanjubh(String danjubh) {
        this.danjubh = danjubh == null ? null : danjubh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.CHUKULX
     *
     * @return the value of STORE_DIAOBOCKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChukulx() {
        return chukulx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.CHUKULX
     *
     * @param chukulx the value for STORE_DIAOBOCKD.CHUKULX
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChukulx(String chukulx) {
        this.chukulx = chukulx == null ? null : chukulx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.DIAORUF
     *
     * @return the value of STORE_DIAOBOCKD.DIAORUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDiaoruf() {
        return diaoruf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.DIAORUF
     *
     * @param diaoruf the value for STORE_DIAOBOCKD.DIAORUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDiaoruf(String diaoruf) {
        this.diaoruf = diaoruf == null ? null : diaoruf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.DIAOCHUF
     *
     * @return the value of STORE_DIAOBOCKD.DIAOCHUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getDiaochuf() {
        return diaochuf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.DIAOCHUF
     *
     * @param diaochuf the value for STORE_DIAOBOCKD.DIAOCHUF
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setDiaochuf(String diaochuf) {
        this.diaochuf = diaochuf == null ? null : diaochuf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.CHENGYUNDW
     *
     * @return the value of STORE_DIAOBOCKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChengyundw() {
        return chengyundw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.CHENGYUNDW
     *
     * @param chengyundw the value for STORE_DIAOBOCKD.CHENGYUNDW
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChengyundw(String chengyundw) {
        this.chengyundw = chengyundw == null ? null : chengyundw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.LUXIAN
     *
     * @return the value of STORE_DIAOBOCKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getLuxian() {
        return luxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.LUXIAN
     *
     * @param luxian the value for STORE_DIAOBOCKD.LUXIAN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setLuxian(String luxian) {
        this.luxian = luxian == null ? null : luxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.CHEXING
     *
     * @return the value of STORE_DIAOBOCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChexing() {
        return chexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.CHEXING
     *
     * @param chexing the value for STORE_DIAOBOCKD.CHEXING
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChexing(String chexing) {
        this.chexing = chexing == null ? null : chexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.TIJI
     *
     * @return the value of STORE_DIAOBOCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getTiji() {
        return tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.TIJI
     *
     * @param tiji the value for STORE_DIAOBOCKD.TIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setTiji(BigDecimal tiji) {
        this.tiji = tiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.CHEPAIH
     *
     * @return the value of STORE_DIAOBOCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getChepaih() {
        return chepaih;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.CHEPAIH
     *
     * @param chepaih the value for STORE_DIAOBOCKD.CHEPAIH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setChepaih(String chepaih) {
        this.chepaih = chepaih == null ? null : chepaih.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.JIHUAFHRQ
     *
     * @return the value of STORE_DIAOBOCKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getJihuafhrq() {
        return jihuafhrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.JIHUAFHRQ
     *
     * @param jihuafhrq the value for STORE_DIAOBOCKD.JIHUAFHRQ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setJihuafhrq(String jihuafhrq) {
        this.jihuafhrq = jihuafhrq == null ? null : jihuafhrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.SHIJI
     *
     * @return the value of STORE_DIAOBOCKD.SHIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShiji() {
        return shiji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.SHIJI
     *
     * @param shiji the value for STORE_DIAOBOCKD.SHIJI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShiji(String shiji) {
        this.shiji = shiji == null ? null : shiji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.LIANXIDH
     *
     * @return the value of STORE_DIAOBOCKD.LIANXIDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getLianxidh() {
        return lianxidh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.LIANXIDH
     *
     * @param lianxidh the value for STORE_DIAOBOCKD.LIANXIDH
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setLianxidh(String lianxidh) {
        this.lianxidh = lianxidh == null ? null : lianxidh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.SHOUHUODZ
     *
     * @return the value of STORE_DIAOBOCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public String getShouhuodz() {
        return shouhuodz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.SHOUHUODZ
     *
     * @param shouhuodz the value for STORE_DIAOBOCKD.SHOUHUODZ
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setShouhuodz(String shouhuodz) {
        this.shouhuodz = shouhuodz == null ? null : shouhuodz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.GONGLI
     *
     * @return the value of STORE_DIAOBOCKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getGongli() {
        return gongli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.GONGLI
     *
     * @param gongli the value for STORE_DIAOBOCKD.GONGLI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setGongli(BigDecimal gongli) {
        this.gongli = gongli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.YUNJIA
     *
     * @return the value of STORE_DIAOBOCKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public Integer getYunjia() {
        return yunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.YUNJIA
     *
     * @param yunjia the value for STORE_DIAOBOCKD.YUNJIA
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYunjia(Integer yunjia) {
        this.yunjia = yunjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STORE_DIAOBOCKD.YUNFEI
     *
     * @return the value of STORE_DIAOBOCKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public BigDecimal getYunfei() {
        return yunfei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STORE_DIAOBOCKD.YUNFEI
     *
     * @param yunfei the value for STORE_DIAOBOCKD.YUNFEI
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    public void setYunfei(BigDecimal yunfei) {
        this.yunfei = yunfei;
    }
}