package com.claude.wmall.jxc.dao.store;

import com.claude.wmall.jxc.domain.store.StoreDiaoBoRkd;
import com.claude.wmall.jxc.domain.store.StoreDiaoboRkdQuery;

import java.util.List;

public interface StoreDiaoBoRkdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreDiaoBoRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreDiaoBoRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreDiaoBoRkd selectByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreDiaoBoRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBORKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreDiaoBoRkd record);

    /**
     * 分页查询调拨入库单列表
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreDiaoBoRkd> selectListByPage(StoreDiaoboRkdQuery query)throws Exception;

    /**
     * 查询单据详情
     * @param danjubh
     * @return
     * @throws Exception
     */
    StoreDiaoBoRkd selectByDanjubh(String danjubh)throws Exception;

    void updateByDanjubh(StoreDiaoBoRkd diaoBoRkd)throws Exception;

    void deleteByDanjubh(String danjubh)throws Exception;
}