package com.claude.wmall.jxc.dao.store;

import com.claude.wmall.jxc.domain.store.StoreKunCunPc;

public interface StoreKunCunPcDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long picih);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreKunCunPc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreKunCunPc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreKunCunPc selectByPrimaryKey(Long picih);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreKunCunPc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUNCUNPC
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreKunCunPc record);
}