package com.claude.wmall.jxc.dao.store;

import com.claude.wmall.jxc.domain.store.StoreShengChanRkd;
import com.claude.wmall.jxc.domain.store.StoreShengchanRkdQuery;

import java.util.List;

public interface StoreShengChanRkdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreShengChanRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreShengChanRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreShengChanRkd selectByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreShengChanRkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_SHENGCHANRKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreShengChanRkd record);

    /**
     * 查询生产入库单列表
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreShengChanRkd> selectListByPage(StoreShengchanRkdQuery query)throws Exception;

    StoreShengChanRkd selectByDanjubh(String danjubh)throws Exception;

    void deleteByDanjubh(String danjubh)throws Exception;

    void updateByDanjubh(StoreShengChanRkd storeShengChanRkd)throws Exception;
}