package com.claude.wmall.jxc.dao.store;

import java.util.List;

import com.claude.wmall.jxc.domain.store.StoreHongZiXsckd;

public interface StoreHongZiXsckdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreHongZiXsckd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreHongZiXsckd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreHongZiXsckd selectByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreHongZiXsckd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_HONGZIXSCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreHongZiXsckd record);
    
    /**
     * 分页查询
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreHongZiXsckd> selectListByPage(StoreHongZiXsckd query)throws Exception;
}