package com.claude.wmall.jxc.dao.store;

import java.util.List;

import com.claude.wmall.jxc.domain.store.StoreZhuangCheCkd;

public interface StoreZhuangCheCkdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long bianhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreZhuangCheCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreZhuangCheCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreZhuangCheCkd selectByPrimaryKey(Long bianhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreZhuangCheCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_ZHUANGCHECKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreZhuangCheCkd record);
    
    
    /**
     * 分页查询采购单
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreZhuangCheCkd> selectListByPage(StoreZhuangCheCkd query)throws Exception;
}