package com.claude.wmall.jxc.dao.store;

import com.claude.wmall.jxc.domain.store.StoreKuCun;
import com.claude.wmall.jxc.domain.store.StoreKuCunKey;

public interface StoreKuCunDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(StoreKuCunKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreKuCun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreKuCun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreKuCun selectByPrimaryKey(StoreKuCunKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreKuCun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUCUN
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreKuCun record);
}