package com.claude.wmall.jxc.dao.store;

import java.util.List;

import com.claude.wmall.jxc.domain.store.StoreKudan;

public interface StoreKudanDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUDAN
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    int deleteByPrimaryKey(String danjubh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUDAN
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    int insert(StoreKudan record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUDAN
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    StoreKudan selectByPrimaryKey(String danjubh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUDAN
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    int updateByPrimaryKeySelective(StoreKudan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_KUDAN
     *
     * @mbggenerated Thu Aug 11 06:30:48 CST 2016
     */
    int updateByPrimaryKey(StoreKudan record);

    /**
     * 分页查询
     *
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreKudan> selectListByPage(StoreKudan query) throws Exception;

    /**
     * 删除库单
     *
     * @param danjubh
     * @throws Exception
     */
    void deleteByDanjubh(String danjubh) throws Exception;

}