package com.claude.wmall.jxc.dao.store;

import com.claude.wmall.jxc.domain.store.StoreChuRuKls;

import java.util.List;

public interface StoreChuRuKlsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long liushuih);
    
    int deleteByKey(String danjubh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreChuRuKls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreChuRuKls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreChuRuKls selectByPrimaryKey(Long liushuih);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreChuRuKls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_CHURUKLS
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreChuRuKls record);

    /**
     * 根据单据编号查询流水列表
     * @param danjubh
     * @return
     */
    List<StoreChuRuKls> selectByDanjuBh(String danjubh)throws Exception;

    /**
     * 删除库单
     * @param danjubh
     * @throws Exception
     */
    void deleteByDanjubh(String danjubh)throws Exception;
}