package com.claude.wmall.jxc.dao.store;

import java.util.List;

import com.claude.wmall.jxc.domain.store.StoreDiaoBoCkd;

public interface StoreDiaoBoCkdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreDiaoBoCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreDiaoBoCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreDiaoBoCkd selectByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreDiaoBoCkd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_DIAOBOCKD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreDiaoBoCkd record);
    
    /**
     * 分页查询
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreDiaoBoCkd> selectListByPage(StoreDiaoBoCkd query)throws Exception;
}