package com.claude.wmall.jxc.dao.store;

import java.util.List;

import com.claude.wmall.jxc.domain.store.StoreYiKuD;

public interface StoreYiKuDDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int deleteByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insert(StoreYiKuD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int insertSelective(StoreYiKuD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    StoreYiKuD selectByPrimaryKey(Long banhao);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKeySelective(StoreYiKuD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STORE_YIKUD
     *
     * @mbggenerated Mon Aug 08 23:37:21 CST 2016
     */
    int updateByPrimaryKey(StoreYiKuD record);
    
    
    /**
     * 分页查询
     * @param query
     * @return
     * @throws Exception
     */
    List<StoreYiKuD> selectListByPage(StoreYiKuD query)throws Exception;
}