package com.claude.wmall.jxc.dao.sale;

import java.util.List;

import com.claude.wmall.jxc.domain.sale.SaleybOrder;

public interface SaleybOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int deleteByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int insert(SaleybOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int insertSelective(SaleybOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    SaleybOrder selectByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int updateByPrimaryKeySelective(SaleybOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int updateByPrimaryKey(SaleybOrder record);
    
    List<SaleybOrder> selectListByPage(SaleybOrder saleybOrder);
}