package com.claude.wmall.jxc.dao.sale;

import com.claude.wmall.jxc.domain.sale.SaleybOrderProduct;

public interface SaleybOrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int insert(SaleybOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int insertSelective(SaleybOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    SaleybOrderProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int updateByPrimaryKeySelective(SaleybOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALE_YBORDER_PRODUCT
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    int updateByPrimaryKey(SaleybOrderProduct record);
}