package com.claude.wmall.jxc.dao.recManage;

import com.claude.wmall.jxc.domain.recManage.CustomerRec;

public interface CustomerRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insert(CustomerRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insertSelective(CustomerRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    CustomerRec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKeySelective(CustomerRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKey(CustomerRec record);
}