package com.claude.wmall.jxc.dao.recManage;

import com.claude.wmall.jxc.domain.recManage.CustomerReceipt;

public interface CustomerReceiptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	int insert(CustomerReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	int insertSelective(CustomerReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	CustomerReceipt selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	int updateByPrimaryKeySelective(CustomerReceipt record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_customer_receiptaddress
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	int updateByPrimaryKey(CustomerReceipt record);
}