package com.claude.wmall.jxc.dao.recManage;

import java.util.List;

import com.claude.wmall.jxc.domain.recManage.CustomerRec;
import com.claude.wmall.jxc.domain.recManage.CustomerReceipt;

public interface CustomerReceiptDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    int insert(CustomerReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    int insertSelective(CustomerReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    CustomerReceipt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    int updateByPrimaryKeySelective(CustomerReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_receiptaddress
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    int updateByPrimaryKey(CustomerReceipt record);

	List<CustomerReceipt> getCustomerReceiptListByCustomerId(String string);

	int deleteByCustomerId(String id);
}