package com.claude.wmall.jxc.dao.recManage;

import java.util.List;

import com.claude.wmall.jxc.domain.recManage.Product;

public interface ProductDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    Product selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    int updateByPrimaryKey(Product record);
    
    List<Product> selectListByPage(Product product);
    
    int updateStatusByCode(Product record);
}