package com.claude.wmall.jxc.dao.recManage;

import com.claude.wmall.jxc.domain.recManage.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKey(Product record);
}