package com.claude.wmall.jxc.dao.recManage;

import java.util.List;

import com.claude.wmall.jxc.domain.recManage.RegionRec;

public interface RegionRecDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insert(RegionRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int insertSelective(RegionRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    RegionRec selectByPrimaryKey(Integer id);
    
    List<RegionRec> selectByRoleName(String roleName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKeySelective(RegionRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Region
     *
     * @mbggenerated Fri Aug 19 13:57:40 CST 2016
     */
    int updateByPrimaryKey(RegionRec record);
    List<RegionRec> selectListByPage(RegionRec product);
    List<RegionRec> getAll();


}