package com.claude.wmall.jxc.domain.sale;

import java.util.Date;

public class SaleybOrderProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.bill_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_name
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_unit
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private String productUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_volume
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Long productVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_number
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Integer productNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_price
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Long productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_sum_money
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Long productSumMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALE_YBORDER_PRODUCT.product_date
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    private Date productDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.id
     *
     * @return the value of SALE_YBORDER_PRODUCT.id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.id
     *
     * @param id the value for SALE_YBORDER_PRODUCT.id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.bill_id
     *
     * @return the value of SALE_YBORDER_PRODUCT.bill_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.bill_id
     *
     * @param billId the value for SALE_YBORDER_PRODUCT.bill_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_id
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_id
     *
     * @param productId the value for SALE_YBORDER_PRODUCT.product_id
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_name
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_name
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_name
     *
     * @param productName the value for SALE_YBORDER_PRODUCT.product_name
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_unit
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_unit
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public String getProductUnit() {
        return productUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_unit
     *
     * @param productUnit the value for SALE_YBORDER_PRODUCT.product_unit
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductUnit(String productUnit) {
        this.productUnit = productUnit == null ? null : productUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_volume
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_volume
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Long getProductVolume() {
        return productVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_volume
     *
     * @param productVolume the value for SALE_YBORDER_PRODUCT.product_volume
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductVolume(Long productVolume) {
        this.productVolume = productVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_number
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_number
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Integer getProductNumber() {
        return productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_number
     *
     * @param productNumber the value for SALE_YBORDER_PRODUCT.product_number
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductNumber(Integer productNumber) {
        this.productNumber = productNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_price
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_price
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Long getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_price
     *
     * @param productPrice the value for SALE_YBORDER_PRODUCT.product_price
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_sum_money
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_sum_money
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Long getProductSumMoney() {
        return productSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_sum_money
     *
     * @param productSumMoney the value for SALE_YBORDER_PRODUCT.product_sum_money
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductSumMoney(Long productSumMoney) {
        this.productSumMoney = productSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALE_YBORDER_PRODUCT.product_date
     *
     * @return the value of SALE_YBORDER_PRODUCT.product_date
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public Date getProductDate() {
        return productDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALE_YBORDER_PRODUCT.product_date
     *
     * @param productDate the value for SALE_YBORDER_PRODUCT.product_date
     *
     * @mbggenerated Mon Aug 29 14:42:03 CST 2016
     */
    public void setProductDate(Date productDate) {
        this.productDate = productDate;
    }
}