package com.claude.wmall.jxc.domain.sale;

import java.math.BigDecimal;
import java.util.Date;

import com.claude.wmall.jxc.domain.common.WmallPager;

public class SaleybOrder extends WmallPager{ 

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.bill_id
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private Integer billId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.bill_date
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private Date billDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.bill_staff
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String billStaff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.bill_user
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String billUser;
	
	
	private String billUserRegion;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private BigDecimal balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.dept
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String dept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.address
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.sx_balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private BigDecimal sxBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.atten
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String atten;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SALE_YBORDER.atten_phone
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	private String attenPhone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.bill_id
	 * @return  the value of SALE_YBORDER.bill_id
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public Integer getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.bill_id
	 * @param billId  the value for SALE_YBORDER.bill_id
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.bill_date
	 * @return  the value of SALE_YBORDER.bill_date
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public Date getBillDate() {
		return billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.bill_date
	 * @param billDate  the value for SALE_YBORDER.bill_date
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.bill_staff
	 * @return  the value of SALE_YBORDER.bill_staff
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getBillStaff() {
		return billStaff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.bill_staff
	 * @param billStaff  the value for SALE_YBORDER.bill_staff
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setBillStaff(String billStaff) {
		this.billStaff = billStaff == null ? null : billStaff.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.bill_user
	 * @return  the value of SALE_YBORDER.bill_user
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getBillUser() {
		return billUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.bill_user
	 * @param billUser  the value for SALE_YBORDER.bill_user
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setBillUser(String billUser) {
		this.billUser = billUser == null ? null : billUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.balance
	 * @return  the value of SALE_YBORDER.balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.balance
	 * @param balance  the value for SALE_YBORDER.balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.dept
	 * @return  the value of SALE_YBORDER.dept
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getDept() {
		return dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.dept
	 * @param dept  the value for SALE_YBORDER.dept
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setDept(String dept) {
		this.dept = dept == null ? null : dept.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.address
	 * @return  the value of SALE_YBORDER.address
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.address
	 * @param address  the value for SALE_YBORDER.address
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.sx_balance
	 * @return  the value of SALE_YBORDER.sx_balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public BigDecimal getSxBalance() {
		return sxBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.sx_balance
	 * @param sxBalance  the value for SALE_YBORDER.sx_balance
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setSxBalance(BigDecimal sxBalance) {
		this.sxBalance = sxBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.atten
	 * @return  the value of SALE_YBORDER.atten
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getAtten() {
		return atten;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.atten
	 * @param atten  the value for SALE_YBORDER.atten
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setAtten(String atten) {
		this.atten = atten == null ? null : atten.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SALE_YBORDER.atten_phone
	 * @return  the value of SALE_YBORDER.atten_phone
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public String getAttenPhone() {
		return attenPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SALE_YBORDER.atten_phone
	 * @param attenPhone  the value for SALE_YBORDER.atten_phone
	 * @mbggenerated  Mon Aug 29 14:42:03 CST 2016
	 */
	public void setAttenPhone(String attenPhone) {
		this.attenPhone = attenPhone == null ? null : attenPhone.trim();
	}

	public String getBillUserRegion() {
		return billUserRegion;
	}

	public void setBillUserRegion(String billUserRegion) {
		this.billUserRegion = billUserRegion;
	}
	
	
}