package com.claude.wmall.jxc.domain.recManage;

public class CustomerReceipt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.customer_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private String customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.address_province
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private String addressProvince;
	private String addressProvinceName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.address_city
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private String addressCity;
	private String addressCityName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.address_county
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private String addressCounty;
	private String addressCountyName;

	public String getAddressProvinceName() {
		return addressProvinceName;
	}

	public void setAddressProvinceName(String addressProvinceName) {
		this.addressProvinceName = addressProvinceName;
	}

	public String getAddressCityName() {
		return addressCityName;
	}

	public void setAddressCityName(String addressCityName) {
		this.addressCityName = addressCityName;
	}

	public String getAddressCountyName() {
		return addressCountyName;
	}

	public void setAddressCountyName(String addressCountyName) {
		this.addressCountyName = addressCountyName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.receiptplace_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private Integer receiptplaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_customer_receiptaddress.addressfull
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	private String receiptplaceName;
	private String addressfull;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.id
	 * @return  the value of t_customer_receiptaddress.id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.id
	 * @param id  the value for t_customer_receiptaddress.id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.customer_id
	 * @return  the value of t_customer_receiptaddress.customer_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.customer_id
	 * @param customerId  the value for t_customer_receiptaddress.customer_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.address_province
	 * @return  the value of t_customer_receiptaddress.address_province
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public String getAddressProvince() {
		return addressProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.address_province
	 * @param addressProvince  the value for t_customer_receiptaddress.address_province
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setAddressProvince(String addressProvince) {
		this.addressProvince = addressProvince == null ? null : addressProvince
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.address_city
	 * @return  the value of t_customer_receiptaddress.address_city
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public String getAddressCity() {
		return addressCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.address_city
	 * @param addressCity  the value for t_customer_receiptaddress.address_city
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity == null ? null : addressCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.address_county
	 * @return  the value of t_customer_receiptaddress.address_county
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public String getAddressCounty() {
		return addressCounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.address_county
	 * @param addressCounty  the value for t_customer_receiptaddress.address_county
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setAddressCounty(String addressCounty) {
		this.addressCounty = addressCounty == null ? null : addressCounty
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.receiptplace_id
	 * @return  the value of t_customer_receiptaddress.receiptplace_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public Integer getReceiptplaceId() {
		return receiptplaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.receiptplace_id
	 * @param receiptplaceId  the value for t_customer_receiptaddress.receiptplace_id
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setReceiptplaceId(Integer receiptplaceId) {
		this.receiptplaceId = receiptplaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_customer_receiptaddress.addressfull
	 * @return  the value of t_customer_receiptaddress.addressfull
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public String getAddressfull() {
		return addressfull;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_customer_receiptaddress.addressfull
	 * @param addressfull  the value for t_customer_receiptaddress.addressfull
	 * @mbggenerated  Fri Aug 19 19:17:47 CST 2016
	 */
	public void setAddressfull(String addressfull) {
		this.addressfull = addressfull == null ? null : addressfull.trim();
	}

	public void setReceiptplaceName(String receiptplaceName) {
		this.receiptplaceName = receiptplaceName;
	}

	public String getReceiptplaceName() {
		return receiptplaceName;
	}
}