package com.claude.wmall.jxc.domain.recManage;

import java.util.Date;
import java.util.List;

import com.claude.wmall.jxc.domain.common.WmallPager;

public class CustomerRec extends WmallPager{
	private List<CustomerReceipt> receiptList;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.shortname
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_type_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Integer customerTypeId;
    				
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.area_province
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    //add
    private String customerTypeName;
    private String areaFull;
    public String getCustomerTypeName() {
		return customerTypeName;
	}

	public void setCustomerTypeName(String customerTypeName) {
		this.customerTypeName = customerTypeName;
	}

	public String getAreaFull() {
		return areaFull;
	}

	public void setAreaFull(String areaFull) {
		this.areaFull = areaFull;
	}

	public String getSalesmanName() {
		return salesmanName;
	}

	public void setSalesmanName(String salesmanName) {
		this.salesmanName = salesmanName;
	}

	private String areaProvince;
	private String areaProvinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.area_city
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String areaCity;
    private String areaCityName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.area_county
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String areaCounty;
    private String areaCountyName;

    public String getAreaProvinceName() {
		return areaProvinceName;
	}

	public void setAreaProvinceName(String areaProvinceName) {
		this.areaProvinceName = areaProvinceName;
	}

	public String getAreaCityName() {
		return areaCityName;
	}

	public void setAreaCityName(String areaCityName) {
		this.areaCityName = areaCityName;
	}

	public String getAreaCountyName() {
		return areaCountyName;
	}

	public void setAreaCountyName(String areaCountyName) {
		this.areaCountyName = areaCountyName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.industry
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.level
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.legalperson
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String legalperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.Contacts
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.telephone
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.salesman_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Integer salesmanId;
    private String salesmanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.currency
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.bank
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.account
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.Region_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.address
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_user_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.create_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.update_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    private Integer approvalStatus;
    private String approvalStatusName;
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.shortname
     *
     * @return the value of t_customer.shortname
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.shortname
     *
     * @param shortname the value for t_customer.shortname
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_type_id
     *
     * @return the value of t_customer.customer_type_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Integer getCustomerTypeId() {
        return customerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_type_id
     *
     * @param customerTypeId the value for t_customer.customer_type_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setCustomerTypeId(Integer customerTypeId) {
        this.customerTypeId = customerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.area_province
     *
     * @return the value of t_customer.area_province
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    
    public String getAreaProvince() {
        return areaProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.area_province
     *
     * @param areaProvince the value for t_customer.area_province
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setAreaProvince(String areaProvince) {
        this.areaProvince = areaProvince == null ? null : areaProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.area_city
     *
     * @return the value of t_customer.area_city
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getAreaCity() {
        return areaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.area_city
     *
     * @param areaCity the value for t_customer.area_city
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setAreaCity(String areaCity) {
        this.areaCity = areaCity == null ? null : areaCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.area_county
     *
     * @return the value of t_customer.area_county
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getAreaCounty() {
        return areaCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.area_county
     *
     * @param areaCounty the value for t_customer.area_county
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setAreaCounty(String areaCounty) {
        this.areaCounty = areaCounty == null ? null : areaCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.industry
     *
     * @return the value of t_customer.industry
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.industry
     *
     * @param industry the value for t_customer.industry
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.level
     *
     * @return the value of t_customer.level
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.level
     *
     * @param level the value for t_customer.level
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.legalperson
     *
     * @return the value of t_customer.legalperson
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getLegalperson() {
        return legalperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.legalperson
     *
     * @param legalperson the value for t_customer.legalperson
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson == null ? null : legalperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.Contacts
     *
     * @return the value of t_customer.Contacts
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.Contacts
     *
     * @param contacts the value for t_customer.Contacts
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.telephone
     *
     * @return the value of t_customer.telephone
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.telephone
     *
     * @param telephone the value for t_customer.telephone
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.salesman_id
     *
     * @return the value of t_customer.salesman_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Integer getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.salesman_id
     *
     * @param salesmanId the value for t_customer.salesman_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setSalesmanId(Integer salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.currency
     *
     * @return the value of t_customer.currency
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.currency
     *
     * @param currency the value for t_customer.currency
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.bank
     *
     * @return the value of t_customer.bank
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.bank
     *
     * @param bank the value for t_customer.bank
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.account
     *
     * @return the value of t_customer.account
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.account
     *
     * @param account the value for t_customer.account
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.Region_id
     *
     * @return the value of t_customer.Region_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.Region_id
     *
     * @param regionId the value for t_customer.Region_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.address
     *
     * @return the value of t_customer.address
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.address
     *
     * @param address the value for t_customer.address
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_user_id
     *
     * @return the value of t_customer.create_user_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_user_id
     *
     * @param createUserId the value for t_customer.create_user_id
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.create_date
     *
     * @return the value of t_customer.create_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.create_date
     *
     * @param createDate the value for t_customer.create_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.update_date
     *
     * @return the value of t_customer.update_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.update_date
     *
     * @param updateDate the value for t_customer.update_date
     *
     * @mbggenerated Wed Aug 17 17:17:07 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public void setApprovalStatus(Integer approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public Integer getApprovalStatus() {
		return approvalStatus;
	}

	public void setApprovalStatusName(String approvalStatusName) {
		this.approvalStatusName = approvalStatusName;
	}

	public String getApprovalStatusName() {
		return approvalStatusName;
	}

	public void setReceiptList(List<CustomerReceipt> receiptList) {
		this.receiptList = receiptList;
	}

	public List<CustomerReceipt> getReceiptList() {
		return receiptList;
	}
}