package com.claude.wmall.jxc.domain.recManage;

import javax.persistence.GeneratedValue;

import com.claude.wmall.jxc.domain.common.WmallPager;

public class Product extends WmallPager{ 
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.id
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.code
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    @GeneratedValue(generator = "UUID")
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.name
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.category
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.spec
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.brand
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.tax
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.boxcode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String boxcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.packagecode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String packagecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.stock
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.stockunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String stockunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.buyunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String buyunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.saleunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String saleunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.volume
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.roughweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Long roughweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.netweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Long netweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.isbatch
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String isbatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.shelflife
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Long shelflife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.taste
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String taste;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.price
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.pagecategory
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String pagecategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.note
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    private String note;
    
    private String status;
    
    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.id
     *
     * @return the value of T_PRODUCT.id
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.id
     *
     * @param id the value for T_PRODUCT.id
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.code
     *
     * @return the value of T_PRODUCT.code
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.code
     *
     * @param code the value for T_PRODUCT.code
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.name
     *
     * @return the value of T_PRODUCT.name
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.name
     *
     * @param name the value for T_PRODUCT.name
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.category
     *
     * @return the value of T_PRODUCT.category
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.category
     *
     * @param category the value for T_PRODUCT.category
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.spec
     *
     * @return the value of T_PRODUCT.spec
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.spec
     *
     * @param spec the value for T_PRODUCT.spec
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.brand
     *
     * @return the value of T_PRODUCT.brand
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.brand
     *
     * @param brand the value for T_PRODUCT.brand
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.tax
     *
     * @return the value of T_PRODUCT.tax
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.tax
     *
     * @param tax the value for T_PRODUCT.tax
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setTax(String tax) {
        this.tax = tax == null ? null : tax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.boxcode
     *
     * @return the value of T_PRODUCT.boxcode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getBoxcode() {
        return boxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.boxcode
     *
     * @param boxcode the value for T_PRODUCT.boxcode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setBoxcode(String boxcode) {
        this.boxcode = boxcode == null ? null : boxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.packagecode
     *
     * @return the value of T_PRODUCT.packagecode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getPackagecode() {
        return packagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.packagecode
     *
     * @param packagecode the value for T_PRODUCT.packagecode
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setPackagecode(String packagecode) {
        this.packagecode = packagecode == null ? null : packagecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.stock
     *
     * @return the value of T_PRODUCT.stock
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.stock
     *
     * @param stock the value for T_PRODUCT.stock
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.stockunit
     *
     * @return the value of T_PRODUCT.stockunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getStockunit() {
        return stockunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.stockunit
     *
     * @param stockunit the value for T_PRODUCT.stockunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setStockunit(String stockunit) {
        this.stockunit = stockunit == null ? null : stockunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.buyunit
     *
     * @return the value of T_PRODUCT.buyunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getBuyunit() {
        return buyunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.buyunit
     *
     * @param buyunit the value for T_PRODUCT.buyunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setBuyunit(String buyunit) {
        this.buyunit = buyunit == null ? null : buyunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.saleunit
     *
     * @return the value of T_PRODUCT.saleunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getSaleunit() {
        return saleunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.saleunit
     *
     * @param saleunit the value for T_PRODUCT.saleunit
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setSaleunit(String saleunit) {
        this.saleunit = saleunit == null ? null : saleunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.volume
     *
     * @return the value of T_PRODUCT.volume
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.volume
     *
     * @param volume the value for T_PRODUCT.volume
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.roughweight
     *
     * @return the value of T_PRODUCT.roughweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Long getRoughweight() {
        return roughweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.roughweight
     *
     * @param roughweight the value for T_PRODUCT.roughweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setRoughweight(Long roughweight) {
        this.roughweight = roughweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.netweight
     *
     * @return the value of T_PRODUCT.netweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Long getNetweight() {
        return netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.netweight
     *
     * @param netweight the value for T_PRODUCT.netweight
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setNetweight(Long netweight) {
        this.netweight = netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.isbatch
     *
     * @return the value of T_PRODUCT.isbatch
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getIsbatch() {
        return isbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.isbatch
     *
     * @param isbatch the value for T_PRODUCT.isbatch
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setIsbatch(String isbatch) {
        this.isbatch = isbatch == null ? null : isbatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.shelflife
     *
     * @return the value of T_PRODUCT.shelflife
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Long getShelflife() {
        return shelflife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.shelflife
     *
     * @param shelflife the value for T_PRODUCT.shelflife
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setShelflife(Long shelflife) {
        this.shelflife = shelflife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.taste
     *
     * @return the value of T_PRODUCT.taste
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.taste
     *
     * @param taste the value for T_PRODUCT.taste
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setTaste(String taste) {
        this.taste = taste == null ? null : taste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.price
     *
     * @return the value of T_PRODUCT.price
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.price
     *
     * @param price the value for T_PRODUCT.price
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.pagecategory
     *
     * @return the value of T_PRODUCT.pagecategory
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getPagecategory() {
        return pagecategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.pagecategory
     *
     * @param pagecategory the value for T_PRODUCT.pagecategory
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setPagecategory(String pagecategory) {
        this.pagecategory = pagecategory == null ? null : pagecategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.note
     *
     * @return the value of T_PRODUCT.note
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.note
     *
     * @param note the value for T_PRODUCT.note
     *
     * @mbggenerated Thu Aug 18 20:04:42 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}