package com.claude.wmall.jxc.domain.recManage;

import com.claude.wmall.jxc.domain.common.WmallPager;

public class RegionRec extends WmallPager {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.name
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.manager_id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private Integer managerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.telephone
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String telephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.email
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.area_province
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String areaProvince;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.area_city
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String areaCity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.area_county
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String areaCounty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_Region.address
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	private String address;

	//审核状态 0：未审核（默认） 1：通过 2：未通过
	private Integer status;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.id
	 * 
	 * @return the value of T_Region.id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.id
	 * 
	 * @param id
	 *            the value for T_Region.id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.name
	 * 
	 * @return the value of T_Region.name
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.name
	 * 
	 * @param name
	 *            the value for T_Region.name
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.manager_id
	 * 
	 * @return the value of T_Region.manager_id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.manager_id
	 * 
	 * @param managerId
	 *            the value for T_Region.manager_id
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.telephone
	 * 
	 * @return the value of T_Region.telephone
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.telephone
	 * 
	 * @param telephone
	 *            the value for T_Region.telephone
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.email
	 * 
	 * @return the value of T_Region.email
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.email
	 * 
	 * @param email
	 *            the value for T_Region.email
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.area_province
	 * 
	 * @return the value of T_Region.area_province
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getAreaProvince() {
		return areaProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.area_province
	 * 
	 * @param areaProvince
	 *            the value for T_Region.area_province
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setAreaProvince(String areaProvince) {
		this.areaProvince = areaProvince == null ? null : areaProvince.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.area_city
	 * 
	 * @return the value of T_Region.area_city
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getAreaCity() {
		return areaCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.area_city
	 * 
	 * @param areaCity
	 *            the value for T_Region.area_city
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setAreaCity(String areaCity) {
		this.areaCity = areaCity == null ? null : areaCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.area_county
	 * 
	 * @return the value of T_Region.area_county
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getAreaCounty() {
		return areaCounty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.area_county
	 * 
	 * @param areaCounty
	 *            the value for T_Region.area_county
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setAreaCounty(String areaCounty) {
		this.areaCounty = areaCounty == null ? null : areaCounty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_Region.address
	 * 
	 * @return the value of T_Region.address
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_Region.address
	 * 
	 * @param address
	 *            the value for T_Region.address
	 * 
	 * @mbggenerated Fri Aug 19 13:57:40 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	
}